config/routes.rb
Rails.application.routes.draw do
  scope(path: '/') { draw :storefront }
  # This line mounts Solidus's routes at the root of your application.
  #
  # Unless you manually picked only a subset of Solidus components, this will mount routes for:
  #   - solidus_backend
  #   - solidus_api
  # This means, any requests to URLs such as /admin/products, will go to Spree::Admin::ProductsController.
  #
  # If you are using the Starter Frontend as your frontend, be aware that all the storefront routes are defined
  # separately in this file and are not part of the Solidus::Core::Engine engine.
  #
  # If you would like to change where this engine is mounted, simply change the :at option to something different.
  # We ask that you don't use the :as option here, as Solidus relies on it being the default of "spree"
  mount Spree::Core::Engine, at: '/'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  # Define routes for the Home, About, and Contact pages
  get 'home', to: 'pages#home'
  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  #get 'index', to: 'pages#index' # Add this line for the index page
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root 'pages#home'

  # Resources for Products and Categories
  resources :products, only: [:index, :search]
  resources :categories, only: [:index]

  # Adding Search with dropdown for categories
  resources :products do
    collection do
      get 'search'
      get 'by_category/:category_id', to: 'products#by_category', as: 'by_category'
    end
  end

  resources :categories, only: [:index, :search]

end

app/models/about.rb
class About < ApplicationRecord
  def self.ransackable_attributes(auth_object = nil)
    ["content", "created_at", "id", "id_value", "title", "updated_at"]
  end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  has_many :cart_items, dependent: :destroy

  def add_product(product, type, quantity = 1)
    current_item = order_items.find_by(product: product, type: type)
    if current_item
      current_item.increment(:quantity, quantity)
    else
      current_item = order_items.build(product: product, type: type, quantity: quantity)
    end
    current_item.save
  end

  def total_price
    order_items.to_a.sum { |item| item.total_price }
  end
  
  # def checkout
  #   order = user.orders.create(total_price: total_price, status: 'pending')
  #   cart_items.each do |item|
  #     order.order_items.create(product: item.product, quantity: item.quantity, price: item.product.price)
  #   end
  #   cart_items.destroy_all
  #   order
  # end

  # def total_price
  #   cart_items.sum { |item| item.quantity * item.product.price }
  # end
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :cart
  belongs_to :product
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products

  # Validations
  validates :name, presence: true, uniqueness: true

  def self.ransackable_associations(auth_object = nil)
    ["products"]
  end

  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "id", "id_value", "name", "updated_at"]
  end
end

app/models/contact.rb
class Contact < ApplicationRecord
  def self.ransackable_attributes(auth_object = nil)
    ["address", "content", "created_at", "email", "facebook", "id", "id_value", "instagram", "phone", "snapchat", "tiktok", "title", "twitter", "updated_at"]
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :order_items, dependent: :destroy

  def total_price
    order_items.to_a.sum { |item| item.total_price }
  end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :product
  belongs_to :order, optional: true
  belongs_to :cart, optional: true
  belongs_to :type

  def unit_price
    product.sale_price || product.price
  end

  def total_price
    unit_price * quantity
  end
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category, optional: true
  has_many :types, dependent: :destroy
  accepts_nested_attributes_for :types, allow_destroy: true

  has_one_attached :image

  # Validations
  validates :product_id, presence: true
  validates :title, presence: true
  # validates :price, numericality: { greater_than_or_equal_to: 0 }

  def self.ransackable_associations(auth_object = nil)
    ["category"]
  end

  def self.ransackable_attributes(auth_object = nil)
    ["category", "category_id", "created_at", "id", "id_value", "image", "inventory", "price", "product_id", "sale_price", "title", "updated_at"]
  end

  scope :on_sale, -> { where.not(sale_price: nil) }
  scope :recently_updated, -> { where('updated_at >= ?', 3.days.ago) }
  scope :recently_added, -> { where('created_at >= ?', 3.days.ago) }
end

app/models/type.rb
class Type < ApplicationRecord
  belongs_to :product
  # validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :cart, dependent: :destroy
  has_many :orders, dependent: :destroy

  after_create :create_cart

  private

  def create_cart
    Cart.create(user: self)
  end
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def show
    @about = About.find_by(id: 1)
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < StoreController
  helper 'spree/products'
  respond_to :html

  def index
    @searcher = build_searcher(params.merge(include_images: true))
    @products = @searcher.retrieve_products

    # Split products into groups of 3 for the homepage blocks.
    # You probably want to remove this logic and use your own!
    homepage_groups = @products.in_groups_of(3, false)
    @featured_products = homepage_groups[0]
    @collection_products = homepage_groups[1]
    @cta_collection_products = homepage_groups[2]
    @new_arrivals = homepage_groups[3]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/checkout_helper.rb
# frozen_string_literal: true

module CheckoutHelper
  def partial_name_with_fallback(prefix, partial_name, fallback_name = 'default')
    if lookup_context.find_all("#{prefix}/_#{partial_name}").any?
      "#{prefix}/#{partial_name}"
    else
      "#{prefix}/#{fallback_name}"
    end
  end
end

app/helpers/orders_helper.rb
# frozen_string_literal: true

require 'truncate_html'
require 'app/helpers/truncate_html_helper'

module OrdersHelper
  include TruncateHtmlHelper

  def truncated_product_description(product)
    truncate_html(raw(product.description))
  end

  def order_just_completed?(order)
    flash[:order_completed] && order.present?
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/taxons_helper.rb
module TaxonsHelper
  def taxon_seo_url(taxon)
    nested_taxons_path(taxon.permalink)
  end
end

app/views/home/_collection.erb
<% if products.length > 0 %>
  <section class="wrapper mb-12">
    <div class="flex items-center justify-between mb-7">
      <h3 class="font-serif text-h4 md:text-h3"><%= title %></h3>
      <%= render "shared/call_to_action", { label: "Shop All", type: 'secondary', url: products_path } %>
    </div>

    <% mobile_classes = 'grid grid-cols-2 gap-4' %>
    <% desktop_classes = 'md:gap-0 md:flex md:snap-x md:justify-between md:snap-mandatory md:overflow-x-auto md:space-x-6' %>

    <ul class="<%= mobile_classes %> <%= desktop_classes %> no-scrollbar">
      <% products.each do |product| %>
        <%= cache [I18n.locale, current_pricing_options, @taxon, product] do %>
          <%= render ProductCardComponent.new(
            product,
            price: product.price_for_options(current_pricing_options),
            additional_classes: 'snap-start shrink-0 md:w-collection-card h-min-content',
            home_collection: true
          ) %>
        <% end %>
      <% end %>
    </ul>
  </section>
<% end %>

app/views/home/_collections_with_call_to_action.html.erb
<section class="grid-container grid-cols-1 gap-7 wrapper py-4 lg:py-12 lg:grid-cols-3">
  <div class="flex flex-col items-center justify-center py-10 px-3">
    <h3 class="text-h2.5 text-center font-serif mb-5">Become the brand everyone talks about.</h3>
    <%= render "shared/call_to_action", { label: "Get Started", url: 'https://solidus.io/get-started', target: '_blank' } %>
  </div>

  <% products.each_with_index do |product, index| %>
    <%
      product_image = product.gallery.images.second || product.gallery.images.first
    %>

    <%= cache [I18n.locale, current_pricing_options, @taxon, product] do %>
      <%= link_to product_path(product) do %>
        <div class="relative bg-gray-50 overflow-hidden rounded-lg h-full md:rounded-xl lg:rounded-2xl">
          <%= render(ImageComponent.new(
            image: product_image,
            class: 'w-full h-full object-cover',
            size: :full,
          )) %>
          <div class="absolute bottom-0 left-0 right-0 flex flex-col items-start w-full gap-y-1 p-3 !pt-0 md:p-6 md:flex-row md:justify-between md:items-center md:gap-y-0 md:gap-x-2">
            <span class="w-full text-body-sm md:text-body">
              <%= product.name %>
            </span>
            <span class="text-body-sm md:text-body font-sans-md price selling">
              $<%= product.price %>
            </span>
          </div>
        </div>
      <% end %>
    <% end %>
  <% end %>
</section>

app/views/home/_featured_product_banner.html.erb
<section class="relative my-4 w-full lg:my-12 bg-red-500">
  <div class="wrapper-mobile-fullwidth">
    <%= render(ImageComponent.new(
      image: product.gallery.images.last,
      size: :full,
      class: 'w-full object-cover aspect-square md:aspect-auto'
    )) %>
    <div class="absolute bottom-0 left-0 right-0 text-center pb-14">
      <span class="rounded-full px-3 py-1 bg-white text-sm text-black mb-2">New</span>
      <h4 class="text-h3 font-serif-md mb-6 text-white md:mb-11 md:text-h2.5"><%= product.name %></h4>
      <%= render "shared/call_to_action", { label: "Shop Now", type: 'secondary', url: product } %>
    </div>
  </div>
</section>

app/views/home/_featured_products.html.erb
<section class="wrapper pt-3 pb-14 md:pb-24">
  <div class="grid-container">
    <div class="col-span-full md:col-span-8 md:max">
      <%= render 'products/featured_product_card', { product: products[0], size: 'big' } %>
    </div>
    <div class="col-span-full flex flex-col gap-y-6 md:col-span-4">
      <% products.each_with_index do |product, index| %>
        <% if index > 0 %>
          <div class="basis-1/2">
            <%= render 'products/featured_product_card', { product: product, size: 'small' } %>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</section>

app/views/home/index.html.erb
<%= render 'featured_products', { products: @featured_products } if @featured_products.try(:any?) %>
<%= render 'collection', { title: "Shop Collection", products: @collection_products } if @collection_products.try(:any?) %>
<%= render 'collections_with_call_to_action', { products: @cta_collection_products[0..1] } if @cta_collection_products.try(:any?) %>
<%= render 'featured_product_banner', { product: @cta_collection_products[2] } if @cta_collection_products && @cta_collection_products.size > 2 %>
<%= render 'collection', { title: "New Arrivals", products: @new_arrivals } if @new_arrivals.try(:any?) %>